// регистрация
export const REGISTRATION_FORM_SENDING = 'REGISTRATION_FORM_SENDING';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

// авторизация
export const AUTHENTIFICATION_FORM_SENDING = 'AUTHENTIFICATION_FORM_SENDING';
export const AUTHENTIFICATION_FORM_FAILED = 'AUTHENTIFICATION_FORM_FAILED';
export const AUTHENTIFICATION_FORM_SUCCESS = 'AUTHENTIFICATION_FORM_SUCCESS';
export const LOG_OUT = 'LOG_OUT';

// изменение профиля
export const USER_INFO_EDITING = 'USER_INFO_EDITING';
export const USER_INFO_FETCHING = 'USER_INFO_FETCHING';
export const USER_INFO_FETCH_SUCCESS = 'USER_INFO_FETCH_SUCCESS';
export const USER_INFO_FETCH_ERRORED = 'USER_INFO_FETCH_ERRORED';
export const USER_INFO_FETCH_STATE_CLEARED = 'USER_INFO_FETCH_STATE_CLEARED';

  // получение постов
export const POSTS_IS_LOADING = 'POSTS_IS_LOADING';
export const POSTS_HAS_ERRORED = 'POSTS_HAS_ERRORED';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';

//получение отдельной статьи
export const ARTICLE_IS_LOADING = 'ARTICLE_IS_LOADING';
export const ARTICLE_HAS_ERRORED = 'ARTICLE_HAS_ERRORED';
export const ARTICLE_FETCH_SUCCESS = 'ARTICLE_FETCH_SUCCESS';
// пагинация
export const SET_ARTICLES_COUNT = 'SET_ARTICLES_COUNT';
export const SET_ARTICLES_PER_PAGE = 'SET_ARTICLES_PER_PAGE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

// отправка статьи
export const ARTICLE_SENDING = 'ARTICLE_SENDING';
export const ARTICLE_SENDING_SUCCESS = 'ARTICLE_SENDING_SUCCESS';
export const ARTICLE_SENDING_ERRORED = 'ARTICLE_SENDING_ERRORED';
export const ARTICLE_STATE_CLEAR = 'ARTICLE_STATE_CLEAR';
export const ARTICLE_CREATING = 'ARTICLE_CREATING';
export const ARTICLE_EDITING = 'ARTICLE_EDITING';
export const ARTICLE_DELETE_CONFIRMING = 'ARTICLE_DELETE_CONFIRMING';
export const ARTICLE_DELETE_CONFIRMING_CANCEL = 'ARTICLE_DELETE_CONFIRMING_CANCEL';
export const ARTICLE_DELETE_SUCCESS = 'ARTICLE_DELETE_SUCCESS';

// лайки
export const ARTICLE_LIKE_FETCHING = 'ARTICLE_LIKE_FETCHING';
export const ARTICLE_LIKE_FETCH_ERRORED = 'ARTICLE_LIKE_FETCH_ERRORED';
export const ARTICLE_LIKE_FETCH_SUCCESS = 'ARTICLE_LIKE_FETCH_SUCCESS';

